[tool.poetry]
name = "audit-compliance-ai"
version = "0.1.0"
description = ""
authors = ["chadrack MAYAMBA"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
